CREATE TABLE IF NOT EXISTS skill_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    instructions TEXT NOT NULL,
    source_path VARCHAR(500),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_skill_definitions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS mcp_servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    transport VARCHAR(20) NOT NULL DEFAULT 'http',
    endpoint VARCHAR(500),
    version VARCHAR(100),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mcp_servers_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS mcp_tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    input_schema TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mcp_tools_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS skill_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR(100) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    operation VARCHAR(50) NOT NULL,
    user_message TEXT,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mcp_call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_name VARCHAR(100) NOT NULL,
    tool_name VARCHAR(100) NOT NULL,
    arguments TEXT,
    result_summary TEXT,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tool_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_name VARCHAR(200),
    description TEXT,
    parameters TEXT,
    category VARCHAR(50) NOT NULL DEFAULT 'general',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    requires_auth BOOLEAN NOT NULL DEFAULT FALSE,
    timeout_seconds INTEGER NOT NULL DEFAULT 60,
    api_url VARCHAR(1000),
    api_method VARCHAR(10),
    api_headers TEXT,
    auth_type VARCHAR(50),
    auth_config TEXT,
    response_path VARCHAR(500),
    built_in BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tool_definitions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS tool_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_name VARCHAR(100) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    operation VARCHAR(50) NOT NULL,
    arguments TEXT,
    result_summary TEXT,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_skill_usage_logs_skill_created
    ON skill_usage_logs (skill_name, created_at);

CREATE INDEX IF NOT EXISTS idx_mcp_call_logs_tool_created
    ON mcp_call_logs (tool_name, created_at);

CREATE INDEX IF NOT EXISTS idx_tool_usage_logs_tool_created
    ON tool_usage_logs (tool_name, created_at);
